### ISSUE TITLE
FEATURE REQUEST: EXPENSIVE RECIPE

### ISSUE THREAD

**Issue by Thelegendking** [Derec-Mods/Mace-Mod#12]
Minecraft Version: 1.20.1
Mod Version: Forge 47.2.19

Hi! Can you change its recipe from one iron block on top to something like this : Iron Block + Nether star + Iron Block
This will make it much more expensive and fitting cost for such a powerful weapon if not overpowered which it deserves imo, thank you for porting this weapon to 1.20.1.

**Comment by DereC4** [comment]
You can use datapacks to change these directly I believe; the majority of the userbase seems fine with the current recipe so I do not want to tip things too far or upset the players

**Comment by DereC4** [comment]
Balanced variants have began to be approved on curseforge, look for them in our mod files!

https://legacy.curseforge.com/minecraft/mc-mods/mace-backport/files
