### ISSUE TITLE
Add wind loads.

### ISSUE THREAD

**Issue by Kaise7** [Derec-Mods/Mace-Mod#5]
Minecraft Version: 1.20.1
Mod Version: 1.20.1

I don't know about mods, but it would be great to have the wind charges next to the mace.

**Comment by DereC4** [comment]
Heyo! Thanks for submitting something. It's 3 in the morning so I'm a bit tired but could you detail your thing a bit more? I'm not sure what you would like to be implemented; what is a wind load?

**Comment by Titoo8899** [comment]
DereC4,
I can help you what the people People with the Wind Charge will. In the new 1.21 Features, Mods etc. give it the Breeze Mob and this mod Drop then the Player kill him the Wind charges (loads) this is a item what the Player give a think of knockback for you can a high of 3 or 4 Blocks higher Jump as normal and can the Mob kill of a new Style

**Comment by DereC4** [comment]
I get what you are trying to say but as of now I don't plan to update with that sadly because i'm busy with work 

try the other wind charge mods there's def one that works well with this mod
