### ISSUE TITLE
Damage cap for 1.12.2

### ISSUE THREAD

**Issue by 80664** [Derec-Mods/Mace-Mod#7]
Minecraft Version:1.12.2
Mod Version:

Can you add a configurable damage cap

Thanks for submitting an issue and I hope you have an awesome day!

**Comment by DereC4** [comment]
Balanced variants have began to be approved on curseforge, look for them in our mod files!

https://legacy.curseforge.com/minecraft/mc-mods/mace-backport/files

**Comment by DereC4** [comment]
Damage cap was also added
